### ISSUE TITLE
Can't make certain fields optional without a jsonize constructor

### ISSUE THREAD

**Issue by SerialVelocity** [rcorre/jsonizer#1]
Hey,

I've got something I am deserialising which has 20 fields or so (third-party api) and some fields are optional. There currently doesn't look like there is an annotation to allow this and I would really prefer not to create a constructor with 20 fields.

**Comment by rcorre** [comment]
Currently, all `jsonize` fields are optional unless you are using the constructor approach. I should probably allow an annotation that allows you to mark fields as 'required', or make 'required' the default and allow the user to mark fields as 'optional'. I'll need to work on making the `@jsonize` attribute more flexible or add new annotations.

**Comment by SerialVelocity** [comment]
Oh, then this bug should be that I am receiving range errors when the
fields aren't found in the json (for object types I think)

**Comment by rcorre** [comment]
It seems I spoke too soon. It looks like I **do** treat all fields as required by default -- I guess I never used jsonizer in a case where fields were missing from the json. I'm going to keep the behaviour of requiring fields by default, but add an optional annotation.
