### ISSUE TITLE
Runtime errors should throw JsonizeException

### ISSUE THREAD

**Issue by rcorre** [rcorre/jsonizer#13]
Create a custom exception type for jsonizer, possibly extending the throw child exception types for different kinds of errors.

Sub-exception types:
- `JsonizeMissingKeyException`: a field marked with `@jsonize(JsonizeOptional.no` was not in the json
- `JsonizeExtraKeyException`: json contained a key not matching a serialized member and `JsonizeIgnoreExtraKeys` is set.
- `JsonizeTypeMismatch`: the `JSON_TYPE` of a json field is incompatible with the object field type.

**Comment by SerialVelocity** [comment]
Maybe combine MissingKey and ExtraKey and make it plural with it storing the list of missing/extra fields? Means less time debugging if there are multiple extra/missing keys
