### ISSUE TITLE
Back @jsonize with a tuple instead of a struct

### ISSUE THREAD

**Issue by rcorre** [rcorre/jsonizer#14]
I believe using a tuple will allow me to move some checks from runtime to compile time.
However, the usage of `@jsonize(args...)` will change to `@jsonize!(args...)`.

**Comment by SerialVelocity** [comment]
Aren't those arguments evaluated at compile time anyway using CTFE?

**Comment by rcorre** [comment]
Yes, I think I just managed to confuse myself.
I was screwing around with CTFE and convinced myself that struct attributes were not available at compile time, so I posted this to remind myself to come back to it.
Looking back on code where I'm assigning enums based on fields of `jsonize`, this seems to be pretty obviously untrue, so I probably won't go for the tuple implementation.
