### ISSUE TITLE
Selective imports cause lots of errors

### ISSUE THREAD

**Issue by SerialVelocity** [rcorre/jsonizer#15]
Having a module such as:

``` d
module test;

private {
  import jsonizer : JsonizeMe, jsonize;
}

public class Test {
  mixin JsonizeMe;
  @jsonize bool field;
}
```

causes lots of exceptions such as:

```
../../../../.dub/packages/jsonizer-0.1.0/src/jsonizer.d(66): Error: template instance hasCustomJsonCtor!T template 'hasCustomJsonCtor' is not defined
../../../../.dub/packages/jsonizer-0.1.0/src/jsonizer.d(106): Error: undefined identifier toJSON, did you mean function _toJSON?
```

I think you may need scoped imports somewhere.

**Comment by SerialVelocity** [comment]
The full list of selective imports I need that I shouldn't are:

``` d
import jsonizer : JsonizeIgnoreExtraKeys, fromJSON, hasCustomJsonCtor, isOptional, jsonizeKey, toJSON;
```

**Comment by rcorre** [comment]
Honestly, I think the whole module structure needs some reorganization.
A user should be able to mark up a type without importing `toJSON`/`fromJSON`. For now, I believe importing `toJSON`/`fromJSON` within the mixin scope will suffice, but for the 1.0 release I'd like to adopt a structure more like most other D projects I've seen. Something like:

```
src/
└── jsonizer
    ├── all         : import everything
    ├── io          : json file read/write
    ├── jsonize     : user-defined-type markups (@jsonize and JsonizeMe)
    └── primitive   : toJSON/fromJSON on primitive types
```

I also need to structure things in a way that I can actually make helper functions like `isOptional` private so they aren't polluting the users namespace. Again, this may just require defining/importing into the scope of the `JsonizeMe` mixin.
