### ISSUE TITLE
Range violation when field doesn't exist

### ISSUE THREAD

**Issue by SerialVelocity** [rcorre/jsonizer#2]
This error means nothing to the end user or developer as they can't figure out what field could not be deserialised

**Comment by rcorre** [comment]
The error messages definitely need improvement.
I am considering adding a custom `JsonizeException` that gets thrown for errors like this to provide better error info and give the end user a chance to recover if they anticipate a possible serialization failure.

**Comment by SerialVelocity** [comment]
So this is probably related to #1. This was happening for object type parsing I think? It wasn't that the type was wrong...

**Comment by rcorre** [comment]
I'll take a look tonight. If you could post the error message, that would be awesome :)
