### ISSUE TITLE
Avoid use of object.factory

### ISSUE THREAD

**Issue by rcorre** [rcorre/jsonizer#21]
On account of `object.factory` possibly being a ['misfeature'](http://forum.dlang.org/thread/ysnfzpvrcvmjdekulfnq@forum.dlang.org#post-zxhfewwwkrujlswcaouz:40forum.dlang.org), avoid using it for handling dynamic type (the 'factory construction' feature of jsonizer).

Dynamic type could be handled by having `JsonizeMe` register a deserialization function for each class by generating a static constructor (this will not conflict with user-defined static ctors -- all static ctors get run).

This could also allow dynamic type construction to support more of the features of static type construction (e.g. remove requirement for a no-args ctor).

**Comment by Zalastax** [comment]
Right now you require the base class to have a default-constructor. Could this be circumvented by having the mixin make a constructor that takes some special object you have created? If the mixin creates the constructor you will have full control  so you might be able to do some helpful assumptions which would remove the need of Object.factory.

**Comment by rcorre** [comment]
I can only generate a constructor only if the user does not define a constructor of their own, as mixin templates are not allowed to overload symbols in the surrounding scope.

I would actually like to do more with contructor generation -- if the user has no custom ctor, by generating one I can automatically support serialization of private/const/immutable members. However, I can't always rely on being able to generate a constructor.

Static constructors are different, as you are allowed to define as many static constructors as you like and they will all get called.

**Comment by Zalastax** [comment]
This might not be an alternative but using mixin-strings could do this right? Or is my point moot and you can do it with static constructors instead?

**Comment by rcorre** [comment]
Huh. You actually _can_ overload using a string mixin, but using string mixins would be even messier than my already questionable mixin templates.

I think static constructors will work in this case. Each class could have a table that maps class names to constructor functions. If a class `Parent` has children `A` and `B`, it might have a table like (rough idea):

```
module mod;
class Parent {
    (Parent function(JSONValue))[string] table; // ["mod.A": &A._fromJSON, "mod.B": &B._fromJSON"
    // Generated functions from mixin:
    static Parent _fromJSON(JSONValue json) {
        // first check for special 'class' field and match to a constructor function
        // otherwise assume it is a 'Parent' and continue as normal
     }

    static void _registerJsonCtor(Parent function(JSONValue) ctor) {
        // register in table, and also try to register in parent of this class (pass all the way up hierarchy)
    }
}
```

**Comment by Zalastax** [comment]
Yeah, string mixins can do anything. My wish would be to make it possible to invoke them without having to write mixin(""). That would enable some really cool DSLs. I hope we can get good reflection support in the future as well. Doing it manually (as in your example above) shouldn't really be needed. See if you have any input to the current discussion: http://forum.dlang.org/thread/rxrlggihbstxxriswwnp@forum.dlang.org

**Comment by rcorre** [comment]
Interesting, I'm glad that people are talking about this, though a lot of that discussion went a bit over my head :)

I'm starting to realize that the static constructor idea is not terribly plausible as:
1. It doesn't work well in the generic case. If the constructor functions take an arbitrary type `T` (as opposed to a `JSONValue`), I'm not sure how I would register them. I was hoping this idea could extend to a more generic serialization API, now I'm not so sure.
2. The static constructor doesn't get run if the module is not imported. Maybe this isn't a risk, as a type that the user expects to use would likely be imported somewhere, but it feels flaky.

**Comment by rcorre** [comment]
Finally managed to [work around](https://github.com/rcorre/jsonizer/commit/6428a28c879418f7b077fadd91adf82aceb6a193) using `Object.factory`. Mixing in `JsonizeMe` to some type `T` registers a handler (`fromJSON!T`) all the way up it's class hierarchy.
