### ISSUE TITLE
Add alternative specifier for "class" when handling class hierarchies

### ISSUE THREAD

**Issue by andrewbenton** [rcorre/jsonizer#23]
Right now, @jsonize looks for the "class" key to determine the class of the subtype.  It would be useful to tell the mixin to override the search for "class" and instead search for "name" or "type" instead when doing class inference.

**Comment by rcorre** [comment]
Yeah, this should be customizeable. I'm just not sure whether that customization belongs in the mixin or in the call to `fromJSON`.

**Comment by andrewbenton** [comment]
Maybe a bit of both?  Have the mixin provide the (overridable) default to `fromJSON` so that you can still override `fromJSON`.  I started looking at something along those lines earlier today.  I'm still pretty new to D, so it's a bit slow going.

**Comment by rcorre** [comment]
My current plan is to let `fromJSON`/`toJSON` take an optional configuration object, which would allow you to customize the key used to look up a type name, as well as configuring some other things that were previously not configurable (e.g. handling of NaN/Inf for floats, whether to serialize enums by name or by value, ect.)

**Comment by rcorre** [comment]
Wow, forgot I had a fix for this but never tagged a release for it.
In `0.6.0`, you can do:

```
JsonizeOptions options;
options.classKey = "someotherkey";
auto obj = json.fromJSON!MyType(options);
```

**Comment by andrewbenton** [comment]
Thanks for the change!  What do you think about using a function to define the map from the JSONValue into the class name over a key lookup?

**Comment by rcorre** [comment]
I'm not sure I understand. Could you give an example?

**Comment by andrewbenton** [comment]
I'd be glad to.  If we have incoming JSON data that contains a key/value which doesn't have the class name, but provides a sufficient hint to derive the class name, then a function/delegate could provide the map between the hint and the class name.

For example, if we have a command stream in an editor:

``` json
[
  {"command":"insert","data":"asdfjkl"},
  {"command":"delete","index":1,"count":2},
  {"command":"modify","location":3,"data":"avg"}
]
```

Then we could define a function to handle the map between "command" and the actual struct/class name.

``` d
string translate(JSONValue obj)
{
    return capitalize(obj["command"].str ~ "Command");
}
```

And then fromJSON could be called as:

``` d
JsonizeOptions options;
options.translator = &translate;
auto obj = json.fromJSON!Command(options);
```
