### ISSUE TITLE
@jsonize with JSONValue member

### ISSUE THREAD

**Issue by andrewbenton** [rcorre/jsonizer#24]
I want to use jsonizer to convert most members, but leave one as a raw JSONValue.  When I try to keep these raw members, jsonizer complains about not having a populateFromJSON or convertToJSON.  It seems like  the JSONValue should just copy over.

**Comment by rcorre** [comment]
Are you saying your type has members of type `JSONValue`? I could probably special case those.

**Comment by rcorre** [comment]
Alright, members of type `JSONValue` will be directly serialized/deserialized. Try `v0.6.0`
