### ISSUE TITLE
cannot jsonize field named `val`

### ISSUE THREAD

**Issue by rcorre** [rcorre/jsonizer#3]
Fields named `val` are shadowed by a variable used in [the mixin](https://github.com/rcorre/jsonizer/blob/master/src/jsonizer.d#L82).

**Comment by rcorre** [comment]
check other local variable names used in mixins as well.

**Comment by SerialVelocity** [comment]
You may be able to fix this just by prepending "this." to every field assignment.

**Comment by rcorre** [comment]
Thanks for pointing that out. As obvious as it sounds, I wasn't thinking of it and was about to try something way too complicated.
