### ISSUE TITLE
Deprecate jsonizer in favor of another library

### ISSUE THREAD

**Issue by rcorre** [rcorre/jsonizer#32]
At this point, there are a few other json serialization frameworks out there, most notably [asdf](https://github.com/tamediadigital/asdf) and [painlessjson](https://github.com/BlackEdder/painlessjson).

Does jsonizer provide features that these do not? If so, what are they?
I originally wrote jsonizer as a way to learn about templates in D, so the code quality and project organization is not the greatest, to say the least.

I'm trying to decide between the following:
1. Deprecate jsonizer in favor of another project
2. Deprecate jsonizer, but try to add its unique functionality to another project
3. Clean up jsonizer and continue to maintain it

I'm not opposed to 2/3 **if** there's important functionality that isn't available elsewhere, but I'd rather not spend a lot of time maintaining it if another project does it better.

CC @deviator , @andrewbenton , @dhansen , @SerialVelocity

**Comment by deviator** [comment]
Wow. In `jsonizer` I and my team use many features such as optional in/out and naming of fields at all structures. We use it for base code of our project and it will be vary sad if you close `jsonizer`.
`asdf` and `painlessjson` have same features at first look (exclude private fields), but API `hasVaryLongKeywords` and simple things looks verbosity. Have you ask mainteiners of `asdf` and `painlessjson` about change API to more brevity?

UPD: hmm, `ignore` isn't equal to `optional`... `asdf` and `painlessjson` has no this key (for me) feature

**Comment by rcorre** [comment]
Thanks for the input. That definitely makes me lean towards maintaining this project. Painlessjson has passed `v1.0`, so I don't think their API is flexible at this point. After looking at the docs for ASDF, it looks like they don't serialize private fields, so I don't think that can really be considered a replacement anymore.

**Comment by andrewbenton** [comment]
I took a look over the painlessjson / asdf / other-json-libraries-in-d and I think that `jsonizer` is definitely the easiest to use.  At first look, one of the big selling points for `painlessjson` is that you are able to do serialization without preparation since it seems that their fields are opt-out instead of opt-in.  I could be missing some other strengths from the other libraries, but I find jsonizer the most powerful and easiest to use.

**Comment by deviator** [comment]
I think if you review logic of serialization, `jsonizer` can be a best solution for serialization/deserialization json:
1. `@jsonize` can be not necessary if names of fields in struct and fields in json are same and no special  in/out behavior (for example optional in, ignore out).
2. `mixin JsonizeMe` can be not necessary if no private fields are must serialized

And if we add possibility working without `std.json` or `stdx.data.json` from vibe.d (reading from json-string to struct and writing from struct to json-string directly) and if it will be faster what with using intermediate `JSONValue` struct it be cool.

**Comment by rcorre** [comment]
Just wanted to give an update here:

I've decided to maintain jsonizer, and I'm going through a big refactoring right now. Hopefully it will be done by the end of the week, and it will make the codebase smaller, cleaner, and easier to maintain. It will fix some issues like #29, and should make it easier to address other issues.

As far as @deviator's suggestions:
1. This will be a significant change in behavior, but I think it would be nice. I'm guessing what you mean is that public fields should be (de)serialized by default? This is what the other frameworks seem to do, and it reduces the amount of boilerplate.
2. This will be trivial after the refactoring. I may change the name of the mixin to `JsonizePrivate` to emphasize that it is only required if you want to (de)serialize non-public members.

**Comment by rcorre** [comment]
Just finished a good portion of the refactoring and released `0.7.1` with one bugfix that came 'for free' with the cleanup. `jsonizer` will not be abandoned in the near future :smile:
