### ISSUE TITLE
Optional Jsonize

### ISSUE THREAD

**Issue by kingsleyh** [rcorre/jsonizer#37]
Hi

The docs say to use 

     @jsonize(JsonizeIn.optional)

This doesn't work and when looking at the code I figured out I needed to use opt not optional

     @jsonize(JsonizeIn.opt)

Just thought I would post this here in case anyone else runs into the issue - and maybe the docs should be updated

**Comment by rcorre** [comment]
Thanks for pointing that out! I've updated the docs in d9b388ef393ca5fd0620f830cd4ebb0e1439e6f5
