### ISSUE TITLE
"writeJSON" parameters are flipped compared to "write" in std.file

### ISSUE THREAD

**Issue by SerialVelocity** [rcorre/jsonizer#4]
Hey, using writeJSON and write is really confusing as the parameters are the other way round for writeJSON. Could you flip them so that they are like the standard library?

**Comment by rcorre** [comment]
Yes. Speaking of API changes, I've also been considering changing `extract` to `fromJSON` for the sake of symmetry (`toJSON`/`fromJSON` vs `toJSON`/`extract`).

**Comment by SerialVelocity** [comment]
I like that change. I really hate "extract".

**Comment by SerialVelocity** [comment]
Oh, wait.
I assume you mean after the api change, there will be toJSON/fromJSON/readJSON/writeJSON, right?

**Comment by rcorre** [comment]
Yes, `extract` will eventually be replaced by `fromJSON`, and `writeJSON` will have its parameters flipped.
