### ISSUE TITLE
Can't deserialize both as exact type and as part of a hierarchy

### ISSUE THREAD

**Issue by dhasenan** [rcorre/jsonizer#40]
In the following code, only one of the unittests pass. You can change which unittest passes by compiling with `-version=Hierarchy`. I would like them both to pass.

When the `deserialize hierarchy` test fails (the default), it fails because of an invalid cast: unsurprisingly, when you don't include a class name explicitly, jsonizer can't figure out which derived class you're talking about.

When the `deserialize direct` test fails (`version=Hierarchy`), it fails with the error: `m2.Derived not registered in Derived`. This is surprising; I registered the type, and I was able to deserialize it by asking for the base type.

```D
module m2;
class Base
{
    mixin JsonizeMe;
    version (Hierarchy)
    {
        @jsonize("class")
        @property
        {
            string className() { return this.classinfo.name; }
            void className(string) {}
        }
    }
}
class Derived : Base
{
    mixin JsonizeMe;
}

@("deserialize hierarchy")
unittest
{
    auto a = new Derived();
    auto b = cast(Derived) a.toJSON.fromJSON!Base;
    assert(b !is null);
}

@("deserialize direct")
unittest
{
    auto a = new Derived();
    auto b = a.toJSON.fromJSON!Derived;
    assert(b !is null);
}
```

**Comment by rcorre** [comment]
Thanks for reporting! Should be fixed in v0.7.5.
