### ISSUE TITLE
staticIota is package-private

### ISSUE THREAD

**Issue by michael-fadely** [rcorre/jsonizer#41]
```
src\jsonizer\exceptions.d(14,8): Deprecation: module `std.typecons` member staticIota is not visible from module exceptions
src\jsonizer\fromjson.d(424,10): Deprecation: module `std.typecons` member staticIota is not visible from module fromjson
```

I don't know off hand if there's a compile-time equivalent of `staticIota`, but I tested `std.range.iota` and it can't serve the same purpose. Perhaps the implementation for `staticIota` should be replicated in the jsonizer codebase somewhere?

**Comment by rcorre** [comment]
Released as `v0.7.6`. Thanks!
